targets:
  $default:
    builders:
      graphql_codegen:
        options:
          scopes:
            - lib/data/anilist/graphql/**.graphql
            - lib/data/kitsu/graphql/**.graphql
          clients:
            - graphql
          outputDirectory: ../models
