import 'package:anikki/data/data.dart';

export 'anikki_action.dart';
export 'consumet_episode.dart';
export 'downloader_filter.dart';
export 'history_entry.dart';
export 'left_drawer_type.dart';
export 'library_entry.dart';
export 'library_settings.dart';
export 'local_file.dart';
export 'media/media.dart';
export 'media_list_entry.dart';
export 'news_entry.dart';
export 'qbittorrent_settings.dart';
export 'schedule_entry.dart';
export 'search_result.dart';
export 'settings.dart';
export 'stream_settings.dart';
export 'sub_or_dub.dart';
export 'torrent/models.dart';
export 'torrent/torrent_source.dart';
export 'torrent_type.dart';
export 'torrest_settings.dart';
export 'transmission_settings.dart';
export 'user_list_enum.dart';
export 'video_player_settings.dart';
export 'watch_list.dart';
export 'watch_list_provider.dart';

typedef AnilistListEntry = Query$GetLists$MediaListCollection$lists$entries;
