name: Github Actions
on: [push, pull_request]

jobs:
  windows-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: "Config"
        run: flutter config --enable-windows-desktop

      - name: Env setup
        run: echo "${{ secrets.SECRETS_VARIABLES }}" > .env

      - name: "Debug build"
        run: flutter build windows --debug

      - name: "Test"
        run: flutter test

  windows-build:
    needs: windows-tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: "Config"
        run: flutter config --enable-windows-desktop

      - name: Env setup
        run: echo "${{ secrets.SECRETS_VARIABLES }}" > .env

      - name: "Setup build tools"
        run: dart pub global activate flutter_distributor

      - name: Assets setup windows x64
        run: cd scripts; .\setup.bat windows-x64; cd ..

      - name: "Release build x64"
        run: flutter_distributor package --platform windows --targets exe --artifact-name=anikki_setup_x64.exe

      - name: Assets setup windows x86
        run: git checkout .; cd scripts; .\setup.bat windows-x86; cd ..

      - name: "Release build x86"
        run: flutter_distributor package --platform windows --targets exe --artifact-name=anikki_setup_x86.exe

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: Windows
          path: dist
          retention-days: 5

  linux-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install Ninja
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev mpv libmpv-dev

      - name: Env setup
        run: echo "${{ secrets.SECRETS_VARIABLES }}" > .env

      - name: "Config"
        run: flutter config --enable-linux-desktop

      - name: "Debug build"
        run: flutter build linux --debug

      - name: "Test"
        run: flutter test

  linux-build:
    needs: linux-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: "Config"
        run: flutter config --enable-linux-desktop

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev mpv libmpv-dev locate
          wget -O appimagetool "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
          chmod +x appimagetool

      - name: Env setup
        run: echo "${{ secrets.SECRETS_VARIABLES }}" > .env

      - name: "Setup build tools"
        run: dart pub global activate flutter_distributor

      - name: Assets setup linux x64
        run: cd scripts && ./setup.sh linux-x64 && cd ..

      - name: "Release build - deb x64"
        run: flutter_distributor package --platform linux --targets deb --artifact-name=anikki_x64.deb

      - name: Assets setup linux x86
        run: git checkout . && cd scripts && ./setup.sh linux-x86 && cd ..

      - name: "Release build - deb x86"
        run: flutter_distributor package --platform linux --targets deb --artifact-name=anikki_x86.deb

      - name: Assets setup linux arm64
        run: git checkout . && cd scripts && ./setup.sh linux-arm64 && cd ..

      - name: "Release build - deb arm64"
        run: flutter_distributor package --platform linux --targets deb --artifact-name=anikki_arm64.deb

      - name: Assets setup linux armv7
        run: git checkout . && cd scripts && ./setup.sh linux-armv7 && cd ..

      - name: "Release build - deb armv7"
        run: flutter_distributor package --platform linux --targets deb --artifact-name=anikki_armv7.deb

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: Linux - deb
          path: dist
          retention-days: 5

  linux-android-build:
    needs: linux-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install Ninja
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev mpv libmpv-dev

      - name: Env setup
        run: echo "${{ secrets.SECRETS_VARIABLES }}" > .env

      - name: "Setup build tools"
        run: dart pub global activate flutter_distributor

      - name: "Assets setup x64"
        run: cd scripts && ./setup.sh android-x64 && cd ..

      - name: "Release build - apk"
        run: flutter_distributor package --platform android --targets apk --artifact-name=anikki_x64.apk

      - name: "Release build - aab"
        run: flutter_distributor package --platform android --targets aab --artifact-name=anikki_x64.aab

      - name: "Assets setup x86"
        run: git checkout . && cd scripts && ./setup.sh android-x86 && cd ..

      - name: "Release build - apk"
        run: flutter_distributor package --platform android --targets apk --artifact-name=anikki_x86.apk

      - name: "Release build - aab"
        run: flutter_distributor package --platform android --targets aab --artifact-name=anikki_x86.aab

      - name: "Assets setup arm64"
        run: git checkout . && cd scripts && ./setup.sh android-arm64 && cd ..

      - name: "Release build - apk"
        run: flutter_distributor package --platform android --targets apk --artifact-name=anikki_arm64.apk

      - name: "Release build - aab"
        run: flutter_distributor package --platform android --targets aab --artifact-name=anikki_arm64.aab

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: Android
          path: dist
          retention-days: 5

  macos-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Env setup
        run: echo "${{ secrets.SECRETS_VARIABLES }}" > .env

      - name: "Config"
        run: flutter config --enable-macos-desktop

      - name: "Debug build"
        run: flutter build macos --debug

      - name: "Test"
        run: flutter test

  macos-build:
    needs: macos-tests
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Env setup
        run: echo "${{ secrets.SECRETS_VARIABLES }}" > .env

      - name: "Config"
        run: flutter config --enable-macos-desktop

      - name: "Setup build tools"
        run: |
          dart pub global activate flutter_distributor
          brew install python-setuptools
          npm install -g appdmg

      - name: Assets setup macos
        run: cd scripts && ./setup.sh darwin-arm64 && cd ..

      - name: "Release build"
        run: flutter_distributor package --platform macos --targets dmg --artifact-name=anikki_arm64.dmg

      - name: Assets setup macos
        run: git checkout . && cd scripts && ./setup.sh darwin-x64 && cd ..

      - name: "Release build"
        run: flutter_distributor package --platform macos --targets dmg --artifact-name=anikki_x64.dmg

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: Macos
          path: dist
          retention-days: 5

  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [windows-build, linux-build, macos-build, linux-android-build]
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Setup dist files
        run: |
          export VERSION=$(cat pubspec.yaml | grep version | cut -d ':' -f 2 | xargs)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

          mkdir dist
          mv Windows/${VERSION}/anikki_setup_x64.exe dist/
          mv Windows/${VERSION}/anikki_setup_x86.exe dist/
          mv Macos/${VERSION}/anikki_x64.dmg dist/
          mv Macos/${VERSION}/anikki_arm64.dmg dist/
          mv Linux\ -\ deb/${VERSION}/anikki_x64.deb dist/
          mv Linux\ -\ deb/${VERSION}/anikki_x86.deb dist/
          mv Linux\ -\ deb/${VERSION}/anikki_arm64.deb dist/
          mv Linux\ -\ deb/${VERSION}/anikki_armv7.deb dist/
          mv Android/${VERSION}/anikki_x64.aab dist/
          mv Android/${VERSION}/anikki_x64.apk dist/
          mv Android/${VERSION}/anikki_x86.aab dist/
          mv Android/${VERSION}/anikki_x86.apk dist/
          mv Android/${VERSION}/anikki_arm64.aab dist/
          mv Android/${VERSION}/anikki_arm64.apk dist/
          ls dist

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          name: v${{ env.VERSION }}
          files: |
            dist/anikki_setup_x64.exe
            dist/anikki_setup_x86.exe
            dist/anikki_x64.dmg
            dist/anikki_x86.dmg
            dist/anikki_x64.deb
            dist/anikki_x86.deb
            dist/anikki_arm64.deb
            dist/anikki_armv7.deb
            dist/anikki_x64.aab
            dist/anikki_x64.apk
